# Generated by Django 3.1.3 on 2020-11-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_title', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('image_url', models.URLField(blank=True)),
                ('description', models.TextField(max_length=400)),
                ('category', models.CharField(choices=[('Fashion', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Books, Movies & Music', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Electronics', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Collectibles & Art', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Home & Garden', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Sporting Goods', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Toys & Hobbies', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Business & Industrial', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Health & Beauty', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Others', 'Others')], max_length=6)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_posted', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
