# Generated by Django 3.1.3 on 2020-11-03 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='listed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_posted',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_comments', to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='user',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='watchedBy', to='auctions.AuctionListing'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('Fashion', (('wc', "Women's Clothing"), ('mc', "Men's Clothing"))), ('Books, Movies & Music', (('book', 'Books'), ('dvd', 'DVDs & Movies'), ('Music', 'Music'))), ('Electronics', (('phone', 'Cell Phones, Smart Watches, & Accessories'), ('pc', 'Computers, Tablets & Network Hardware'), ('tv', 'TV, Video & Home Audio Electronics'))), ('Collectibles & Art', (('collec', 'Collectibles'), ('sport', 'Sports Memorabilia, Fan Shop & Sports Cards'), ('art', 'Art'))), ('Home & Garden', (('furnit', 'Furniture'), ('decor', 'Home Decor'))), ('Sporting Goods', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Toys & Hobbies', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Business & Industrial', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Health & Beauty', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Others', 'Others')], max_length=6),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
