# Generated by Django 3.1.3 on 2020-11-03 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201103_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented_by',
            new_name='commented_by_whom',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_by_whom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
