# Generated by Django 3.1.3 on 2020-11-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201103_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
