# Generated by Django 3.1.3 on 2020-11-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='starting_bid',
            new_name='current_bid',
        ),
    ]
