# Generated by Django 3.1.3 on 2020-11-06 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201106_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='highest_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
